title: "Документация"
description: A Jekyll theme for documentation
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://inquisitorgray.github.io" # the base hostname & protocol for your site, e.g. http://example.com

exclude: ["documentation_v3_7/"]

destination: docs/

collections:
  docs:
    output: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: sql
    css_class   : 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
remote_theme: pmarsceill/just-the-docs
#theme: just-the-docs
color_scheme: custom_colors

search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 6
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: false
