title: "Документация DTM"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: sql
    css_class   : 'syntax-highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
remote_theme: pmarsceill/just-the-docs
#color_scheme: corporate_colors
lang: ru
search_enabled: true

