# This is a basic workflow to help you get started with Actions

name: drawio-export-alt

# Controls when the action will run. 
on:
  push:
#  pull_request:
#  pull_request_target:
    paths:
      - '**.xml'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  drawio-export:
    runs-on: ubuntu-latest
      
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: file_changes
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: check-xml-and-copy
        run: |
          pwd
          ls
          echo "All: ${{ steps.file_changes.outputs.all }}"
          echo "Added: ${{ steps.file_changes.outputs.added }}"
          echo "Removed: ${{ steps.file_changes.outputs.removed }}"
          echo "Renamed: ${{ steps.file_changes.outputs.renamed }}"
          echo "Modified: ${{ steps.file_changes.outputs.modified }}"
          echo "Added+Modified: ${{ steps.file_changes.outputs.added_modified }}"
          files_added_modified_renamed='${{ steps.file_changes.outputs.files_added_modified }} ${{ steps.file_changes.outputs.renamed }}'
          echo '${files_added_modified_renamed}'
          srcfilepath="TMP/XML/"
          fileCnt=0
          for changed_file in ${files_added_modified_renamed}; do
            fullfilename=${changed_file}
            filename=$(basename "${fullfilename}")
            ext="${filename##*.}"
            echo "${ext}"
            if [ "${ext}" = "xml" ]
            then
              srcfilename="${srcfilepath}${filename}"
              echo "${srcfilename}"
              cp "${fullfilename}" "${srcfilename}"
              fileCnt=${fileCnt}+1
            fi
          done
          if [ "${fileCnt}" -eq 0 ]
          then
          ::exit::neutral
          fi
          ls "${srcfilepath}"

      - name: Export drawio files to svg files
        uses: rlespinasse/drawio-export-action@v1.x
        with:
          path: 'TMP/XML/'
          format: svg
          output: 'TMP/SVG/'
          transparent: true

      - name: removeTMPXML
        run: rm TMP/XML/*.xml

      - run: |
          ls TMP/SVG/
          files_added_modified_renamed='${{ steps.file_changes.outputs.files_added_modified }} ${{ steps.file_changes.outputs.renamed }}'
          #destfilepath=cat ${{ env.GITHUB_WORKSPACE }} "/TMP/SVG/"
          destfilepath="TMP/SVG/"
          for changed_file in ${files_added_modified_renamed}; do
            fullfilename=${changed_file}
            filename=$(basename "${fullfilename}")
            ext="${filename##*.}"
            if [ "${ext}" = "xml" ]
            then
              filename=$(basename "${fullfilename}" "xls")
              echo "${filename}"
              filename="${filename}.svg"
              echo "${filename}"
              destfilename="${destfilepath}${filename}"
              echo "${destfilename}"
              fullfilename=$(dirname "${changed_file})/${filename}"
              cp "${destfilename}" "${fullfilename}"
            fi
          done

      - name: removeTMPSVG
        run: rm TMP/SVG/*.svg

      - name: Get author and committer info from HEAD commit
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v4.9.2
        with:
          commit_message: "docs: sync draw.io exported files"
          commit_user_name: "${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          commit_user_email: "${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          commit_author: "${{ env.GIT_COMMIT_AUTHOR }}"