# This is a basic workflow to help you get started with Actions

name: get-html

# Controls when the action will run. 
on:
  page_build:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  html-export:
    runs-on: ubuntu-latest
      
    steps:

      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Check _site folder
        run: |
          ls .
          ls ./_site
          
